#!/usr/bin/env python3


def kaneki(num=1000, lim=0, verbose=False, sub=7):
    while num > lim:
        print(f"{num} - {sub} = {num - 7}" if verbose else num - sub)
        num -= sub


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Kaneki Ken number generator")
    parser.add_argument(
        "num", type=int, default=1000, help="number to start with", nargs="?"
    )
    parser.add_argument("-l", "--lim", type=int, default=0, help="number to stop after")
    parser.add_argument("-s", "--sub", type=int, default=7, help="number to subtract")
    parser.add_argument(
        "-v",
        "--verbose",
        help="print full equations instead of results only",
        action="store_true",
    )
    args = parser.parse_args()

    kaneki(**vars(args))
